inn=int(input("enter integer number"))
strr=str(input("enter String value"))
flo=float(input("enetr the float value"))
boo=bool(input("enter the boolean value"))
coo=complex(input("enter the complex value"))
print(type(inn))
print(type(strr))
print(type(flo))
print(type(boo))
print(type(coo))